storages/backends/s3boto.py

Without this, Django 1.7 migrations fail with 
`ValueError: Cannot serialize: <storages.backends.s3boto.S3BotoStorage object at 0x1050a1358>
There are some values Django cannot serialize into migration files.
`

Made S3BotoStorage deconstructible so that Django can migrate it.

---

storages/__init__.py

`warnings.simplefilter('always')`
- This filter applies not just to the `storages` package, but to the entire Django project in which it's being used.
- This filter causes warnings to be printed to the console [**every single time** the code runs past them](https://docs.python.org/3.4/library/warnings.html#the-warnings-filter).
For example, the project I work on uses Django's `strip_tags()` function to create the `text/plain` part of multipart emails, and when using Django 1.6 and Python 3.3+, there are two `DeprecationWarning`s about impending changes to the `HTMLParser` API when `strip_tags()` is used:
```
/home/vagrant/.venv/lib/python3.4/site-packages/django/utils/html.py:121: DeprecationWarning: The strict argument and mode are deprecated.
HTMLParser.__init__(self, strict=False) …
```

Ripping out ridiculous 'always' warning filter

---

storages/backends/ftp.py

Apparently various FTP servers are inconsistent in NLST command output. Some output only filenames, others output paths. This fix supports both.

Fix exists and add modified_time in FTP storage

---

docs/backends/apache_libcloud.rst

Otherwise we'll get `Unable to create libcloud driver type libcloud.storage.types.GOOGLE_STORAGE: Invalid module path` ...

Fix libcloud provider type for GCS in Docs

---

.travis.yml
storages/backends/apache_libcloud.py
storages/backends/azure_storage.py
storages/backends/couchdb.py
storages/backends/database.py
storages/backends/ftp.py
storages/backends/hashpath.py
storages/backends/image.py
storages/backends/mogile.py
storages/backends/mongodb.py
storages/backends/overwrite.py
storages/backends/s3boto.py
storages/backends/sftpstorage.py
storages/backends/symlinkorcopy.py
storages/compat.py
tox.ini

As per the [deprecation note](https://docs.djangoproject.com/en/dev/releases/1.8/#support-for-the-max-length-argument-on-custom-storage-classes).

Django 1.8+ compatibility

---

README.rst

Specifically, `force_bytes` is not available in `Django` 1.4.
https://github.com/jschneier/django-storages/blob/1.2.1/storages/backends/s3boto.py#L12

Removed mention of compatibility with Django 1.4 which still receives extended support

---

storages/backends/gs.py
tests/settings.py
tests/test_gs.py

The property name for GSBotoStorage must be the same as S3BotoStorage.

change Google Storage setting to gzip from is_gzipped

---

storages/backends/ftp.py

Since django's ``File`` class expects a ``name`` atribute, I renamed the ``_name`` attribute to match.

django's File class expects an attribute 'name'

---

storages/compat.py

StorageMixin is supposed to isolate the new `max_length` feature to
Django-1.8 and later, but it wasn't actually doing anything because the MRO
is backwards.

Reverse mixin order, otherwise StorageMixin is ineffective.

---

AUTHORS
MANIFEST.in
requirements-tests.txt
setup.py
storages/backends/dropbox.py
tests/test_dropbox.py
tox.ini

- Supports Dropbox oAuth API
- Added with unittests
- Maybe you want some doc in this pull request ?
Further:
- Support auth with API key and secret
- Ensure locations are great

Added dropbox storage

---

docs/backends/amazon-S3.rst

I think adding AWS_AUTO_CREATE_BUCKET setting in S3's documentation could save some time for people using this package.

[documentation][S3] adding AWS_AUTO_CREATE_BUCKET

---

storages/backends/apache_libcloud.py

This fixes a few issues I've encountered with the ``apache_libcloud`` backend (using Rackspace Cloud Files). These fixes follow the implemlementation of the S3 backend.
- ``file.read(n)`` was returning the whole file regardless of the num_bytes parameter
- Accessing ``file.name`` no longer gives an ``AttributeError``
- Initialising the ``.file`` attribute to an empty ``BytesIO`` object caused errors when trying to load the file into ``Pillow``

Libcloud fixes

---

storages/backends/apache_libcloud.py

There is an issue with libcloud providers that haven't implemented get_object_cdn_url in the libcloud library. This commit integrates changes from https://github.com/pydanny/dj-libcloud and Fixes #68

Fix url lookup for unimplemented providers

---

storages/backends/s3boto.py
tests/test_s3boto.py

S3BotoStorageFile's write method was not initiating the multipart upload with encryption on, even when ```AWS_S3_ENCRYPTION``` was True in the settings

use encryption setting for S3BotoStorageFile multipart uploads

---

storages/backends/s3boto.py

SVG images are mostly text and they compress really well, this should improve performance for SVG static files

Enable GZipping of SVG files automatically in S3Boto Storage

---

storages/backends/s3boto.py
tests/test_s3boto.py

It's often inconvenient to instantiate a new instance of `S3BotoStorage` just to change the expiration of URLs.  Instead I'd like to (optionally) pass the new expiration with each call to `S3BotoStorage.url`.
```python
pic = MyModel.objects.get(...).picture
pic.storage.url(pic.name)  # default expiration
pic.storage.url(pic.name, expire=600)  # custom expiration
```
Happy to make adjustments or take another approach. Thanks!

Optionally override querystring_expire in S3BotoStorage.url

---

storages/backends/gs.py

GSBotoStorage inherits this method from its parent class, S3BotoStorage:
```
def connection(self):
if self._connection is None:
self._connection = self.connection_class(
self.access_key,
self.secret_key,
is_secure=self.use_ssl,
calling_format=self.calling_format,
host=self.host,
port=self.port,
proxy=self.proxy,
proxy_port=self.proxy_port
)
return self._connection
```
Note the `host=self.host`.
The value of this setting for GSBotoStorage used to be derived from S3BotoStorage as well. The value in the parent class was: `host = setting('AWS_S3_HOST', S3Connection.DefaultHost)`, which resolved to 's3.amazonaws.com' instead of the correct 'storage.googleapis.com'.
This fixed #124 for me.

Added host setting to GSBotoStorage (fixes #124)

---

storages/backends/dropbox.py
tests/test_dropbox.py

Improvements to Dropbox storage backend.
- Fixed "exists" check.
- Added "url" method.

Feature dropbox url

---

MANIFEST.in

The tarball on PyPI has some artifacts in the `tests` folder right now (`.pyc`
files) which should not be shipped. Changing the directives to be more precise
as to what gets includes fixes this for future release tarballs.

Be more precise about recursive includes.

---

docs/backends/amazon-S3.rst

Add documentation for AWS_QUERYSTRING_AUTH and AWS_QUERYSTRING_EXPIRE.
See
https://bitbucket.org/david/django-storages/issues/51/please-improve-s3-storage-documentation
and https://github.com/jschneier/django-storages/issues/139.

Document AWS_QUERYSTRING_* settings.

---

README.rst

This was needed when the name was django-storages-redux now is not the case.

Is not a fork anymore

---

docs/backends/sftp.rst
requirements-tests.txt
storages/backends/sftpstorage.py
tests/test_sftp.py
tox.ini

- Added all parameters in `__init__`
- Fixed `SFTPFile.read()`
- Added tests
- Moved documentation from module comments to docs/

Improved SFTP storage

---

docs/backends/ftp.rst
storages/backends/ftp.py
tests/test_ftp.py

- Made some fixes in FTP Storage
- Added ``seek(0)`` to ``_read``, for ensure readability
- Added readlines method to FTP files
- Added (almost) 90% coverage for FTP

Added FTP readlines and fix storage init argument

---

docs/backends/amazon-S3.rst

The docs were missing info about param responsible for enabling server-side encryption.

Added info about AWS_S3_ENCRYPTION.

---

storages/utils.py
tests/test_utils.py

This ease the way to detect a setting and raise an error if unfound.
With tests ;)

Added strict mode to utils.setting()

---

storages/backends/s3boto3.py
tests/settings.py
tests/test_s3boto3.py

Django expects a naive datetime from the [modified_time()] method.
Django 1.10 adds a [get_modified_time()] method which respects USE_TZ.
This commit fixes modified_time(), adds get_modified_time(), and adds
relevant tests.
[modified_time()]: https://docs.djangoproject.com/en/1.10/ref/files/storage/#django.core.files.storage.Storage.modified_time
[get_modified_time()]: https://docs.djangoproject.com/en/1.10/ref/files/storage/#django.core.files.storage.Storage.get_modified_time

Fix TZ awareness in S3Boto3Storage

---

storages/backends/s3boto3.py

Looks like boto3 changed some keyword arguments and this prefix forgot to be capitalised

Fix #189 - preload_metadata option on s3boto3

---

storages/backends/azure_storage.py
storages/backends/couchdb.py
storages/backends/database.py
storages/backends/dropbox.py
storages/backends/ftp.py
storages/backends/gs.py
storages/backends/hashpath.py
storages/backends/image.py
storages/backends/mogile.py
storages/backends/overwrite.py
storages/backends/sftpstorage.py
storages/backends/symlinkorcopy.py

Dear Josh,
I start using this library recently, and want to thank you for maintaining it! And also thangs to all authors and participants for their contribution!
I found that some of the storages doesn't decorated by `@deconstructible`. But this is required in case of passing storage as a parameter into FileField.
Can it be included in future versions?

All storage classes are deconstructible

---

storages/backends/s3boto.py

to allow detection of changes in gzipped files by MD5 SUM in the same
way as for non gzipped files

Freeze modification time when gzipping files to S3

---

storages/backends/sftpstorage.py

Fixes both a TypeError when importing the storage backed and access to the SFTP_STORAGE_HOST value.

Fix host access in SFTPStorage

---

storages/backends/s3boto.py

We're developing a EU project using this package, to interface nicely with AWS S3 storage. When trying to create a bucket automatically, this error is thrown:
```
S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>IllegalLocationConstraintException</Code>
<Message>The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.</Message>
<RequestId>XXX</RequestId>
<HostId>XXX</HostId>
</Error>
```
Turns out the `create_bucket` can take a `location` argument, but it's not in use currently.
From [the documentation](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region): 
> If you use a region other than the US East (N. Virginia) endpoint to create a bucket, you must set the …

Add location to the create_bucket parameters

---

tests/test_s3boto.py
tests/test_s3boto3.py

Fixes warnings of the form "DeprecationWarning: Please use assertEqual instead." when running tests with warnings enabled.

Use assertEqual in place of deprecated assertEquals

---

docs/backends/amazon-S3.rst
docs/backends/azure.rst
docs/backends/database.rst
docs/backends/dropbox.rst
docs/backends/ftp.rst
docs/backends/mogilefs.rst
docs/backends/sftp.rst

Hello,
I made small improvements syntax of docs eg.t:
- use definition lists to settings list - it looks better,
- use ``.. note:: `` for notes,
- fix case of word "optional" in whole docs,
Using definitions lists require some changes in text or reorder paragraph, so I tried unify them.

Improve syntax of docs

---

CHANGELOG.rst
storages/backends/s3boto3.py
tests/test_s3boto3.py

Use a different boto3 session for each instance of the S3 connection.
---
Resurrecting from PR #200 as upstream does not appear to be moving on a change. This fixes the race as far as django-storages is concerned.

Fix S3Boto3Storage to avoid race conditions in a multi-threaded WSGI environment

---

requirements-tests.txt
tox.ini

Newer version has removed deprecated code. Fixes deprecation warning when running tests with warnings enabled like:
```
.../django-storages/lib64/python3.5/site-packages/pytest_cov/plugin.py:37: DeprecationWarning: type argument to addoption() is a string 'int'. For parsearg this should be a type. (options: ('--cov-fail-under',))
help='Fail if the total coverage is less than MIN.')
```

Allow newer versions of pytest-cov for tests

---

storages/backends/s3boto3.py

boto3 version has never contained a '-'. Likely copied over from boto which did
use '-' at one time.

Remove unnecessary '-' parsing from boto3 version

---

storages/backends/s3boto3.py

The current implementation throws an `ImproperlyConfigured` error instead of creating the bucket. This occurs even when `AWS_AUTO_CREATE_BUCKET` has been set to true.

S3Boto3Storage: Fix _get_or_create_bucket

---

README.rst

Change badge image url to shields.io

---

docs/backends/apache_libcloud.rst

I try to configure django-storages to use google cloud storage refer to this file,
but I think it would be better to add apache-libcloud installation on this guideline,
so noob people like me won't need to have the exception first because know that must install apache-libcloud first.

add apache-libcloud installation note

---

docs/conf.py

Updates the 2011-2013 copyright stanza to say 2011-2017. 
The copyright assignee should maybe be reviewed too ("Copyright 2011-2017, django-storages maintainers" maybe).

Update documentation copyright years

---

AUTHORS
storages/backends/s3boto3.py

Hey folks, the only change this makes is to use `bucket_params` when calling `bucket.create()`.
I'm not sure the best way to test this and would love some advice. Thanks!
Resolves #257.

#257: S3Boto3Storage bucket_params

---

docs/backends/amazon-S3.rst

When using the key "Cache-Control" in AWS_S3_OBJECT_PARAMETERS, I got this error:
> ValueError: Invalid extra_args key 'Cache-Control', must be one of: ACL, CacheControl, ContentDisposition, ContentEncoding, ContentLanguage, ContentType, Expires, GrantFullControl, GrantRead, GrantReadACP, GrantWriteACP, Metadata, RequestPayer, ServerSideEncryption, StorageClass, SSECustomerAlgorithm, SSECustomerKey, SSECustomerKeyMD5, SSEKMSKeyId, WebsiteRedirectLocation
I fixed it by replacing "Cache-Control" with "CacheControl".
I fixed the documentation to use the correct key, and to remove the word arbitrary, since it doesn't seem arbitrary to me.
I was using these package versions:
boto3 1.4.4
botocore 1.5.19
django-storages 1.5.2    
s3transfer 0.1.10

Correct example in documentation of S3 parameters

---

storages/backends/s3boto.py
storages/backends/s3boto3.py

Add support for reading the AWS_SESSION_TOKEN and AWS_SECURITY_TOKEN from the environment.
Verified this works as expected in AWS Lambda.

Add support for AWS_SESSION_TOKEN and AWS_SECURITY_TOKEN

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Not a 100% sure it's the best approach, but there it is: my attempt to address #216.
I feel that `_encode_name` and `_decode_name` are starting to lose their naming/meaning values since they now end up doing almost the same thing.
Also, I didn't know what to precisely test. The only thing I know for sure is that the test I added fail without the switch from `smart_str` to `smart_text`.

Apply smart_text on file names in python2.7 [s3boto3]

---

docs/backends/amazon-S3.rst

Included note indicating that AWS_S3_CUSTOM_DOMAIN must *not* end in a slash. It is required that `STATIC_URL` must end in a trailing slash, and if users are using CloudFront, their `STATIC_URL` and `AWS_S3_CUSTOM_DOMAIN` values will be the same. It is very easy for users to miss the trailing `/` and instead set `AWS_S3_CUSTOM_DOMAIN = STATIC_URL` which results in a double-slash in the static URL's (e.g. `https://mydomain.com//staticasset.jpg`).

Update to Amazon S3 Documentation

---

storages/backends/apache_libcloud.py

Please see the docs here for reference to this paremter.
https://libcloud.readthedocs.io/en/latest/compute/drivers/gce.html
Perhaps the docs should be updated to reflect this.

Added project support to GCS through LibCloud

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Adds support for already gzipped content to S3 storage to the boto3 backend #263

---

AUTHORS
docs/backends/gcloud.rst
storages/backends/gcloud.py
storages/backends/google.py
storages/backends/gs.py
storages/backends/s3boto.py
storages/utils.py
tests/test_gcloud.py
tests/test_s3boto.py
tests/test_utils.py
tox.ini

Based on https://github.com/jschneier/django-storages/pull/146
This uses the native `gcloud-python` library, which is recommended by Google for production setups and allows finer-grained authentication than current solutions (which only work when Google Cloud Storage is used in S3 compatibility mode).

Add Google Cloud Storage backend using the gcloud-python library

---

.gitignore
AUTHORS
storages/backends/sftpstorage.py
tests/test_sftp.py

Fixed error described in https://github.com/jschneier/django-storages/issues/118

Fix issue #118

---

storages/backends/s3boto3.py
storages/utils.py
tests/test_s3boto3.py
tests/test_utils.py

Combine the identical s3boto3 and s3boto implementations of safe_join()
and its tests to reduce code duplication.
Fixes #248

Fix S3 safe_join() to allow colons

---

storages/backends/s3boto.py

Calling `S3BotoStorage._save` writes to `_entries` if `preload_metadata`
is True. Future access to `_entries` is limited as the property `entries` only
loads metadata for the bucket if `_entries` is empty, which due to `_save`
it may not be. This in turn causes `exists` to incorrectly return False for
existent files.

Avoid incorrect behaviour of S3BotoStorage.exists

---

CHANGELOG.rst
storages/utils.py
tests/test_utils.py

Regression introduced in 895a068fcf3f23a6b71294c5b4b67a822df6e642
---
This regression was my fault. If the PR looks good, I'm hoping this can go out in a bug fix release as 1.6.0 has broken some of my projects. Thanks!

Fix safe_join to allow joining a base path with an empty string

---

.travis.yml
setup.cfg
setup.py
storages/backends/apache_libcloud.py
storages/backends/azure_storage.py
storages/backends/dropbox.py
storages/backends/ftp.py
storages/backends/gcloud.py
storages/backends/s3boto.py
storages/backends/s3boto3.py
storages/backends/sftpstorage.py
tests/test_dropbox.py
tests/test_ftp.py
tests/test_gcloud.py
tests/test_gs.py
tests/test_s3boto.py
tests/test_s3boto3.py
tests/test_sftp.py
tests/test_utils.py
tox.ini

Reduces need to think and order imports, simply let the tool do it. Provides more consistent code style across Python modules by always ordering imports a single way.
Use same configuration as Django project.

Integrate isort and use it to consistently sort imports across files

---

requirements-tests.txt
tox.ini

* Fixed typo dropbox>=7.21 -> dropbox>=7.2.1
* Alphabetized tox dependencies
* In requirements-tests.txt, change google-cloud>=0.25.0 ->
google-cloud-storage>=0.22.0 to match tox.ini

Sync dependency versions between requirements-tests.txt and tox.ini

---

CHANGELOG.rst
storages/utils.py
tests/test_utils.py

Regression introduced in 895a068fcf3f23a6b71294c5b4b67a822df6e642
Partially reverts 39a2a7a8c08eadd2952cab485ea76434ae86b12f
---
@jschneier Apologies for the 2nd round of regression fixes. I believe I've covered all edge cases with this fix. I have added _many_ more unit tests and more thoroughly tested against my own projects. All feedback welcome. If the diff looks good, I'd appreciate if a new release could get cut as my previous changes to `safe_join()` is broken. Thanks!

Fix safe_join to handle trailing slash with intermediate paths

---

.travis.yml
tox.ini

Fall under the general umbrella of linting the project. Run all linting tools as one stage of testing.
Added @jleclanche's suggestion from #338.

Consolidate flake8 & isort tox envs to a single lint env

---

requirements-tests.txt
tests/test_dropbox.py
tox.ini

The client module was removed from the library.

Fix Dropbox tests to work with version 8.0.0

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Avoids unnecessary API requests to fetch and create the bucket when simply checking if a key exists.
https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.head_object

Simplify S3Boto3Storage.exists() by using boto3's head_object()

---

.gitignore
AUTHORS
storages/backends/gcloud.py
tests/test_gcloud.py

[gcloud] Add support for MIME type

---

CHANGELOG.rst
storages/backends/dropbox.py
tests/test_dropbox.py

Fix DropBoxStorage.url

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Documentation for boto3 recommends a session per thread - https://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading-multiprocessing
As the storage class is (usually) only instantiated once per process, we need to set a thread local for each thread/connection used.
Fixes #268

Create a session/connection per thread for s3boto3

---

tests/test_s3boto3.py

See: https://github.com/jschneier/django-storages/issues/367
@jschneier This is the failing tests.
With a new implementation Django saves intermediate files, so you can have two files with the same content but with different names ([here](https://code.djangoproject.com/ticket/28055) is the closed issue on Django Issue Tracker).
You can see it [here](https://github.com/django/django/blob/master/django/contrib/staticfiles/storage.py#L304) — `self._save` is called twice with the same content but with different names (it is not visible at first because `hashed_name` is recalculated just before `save`).
Django-Storages' code assumes that the content wasn't read before, but it is not the case with new Django's implementation. File content is already read, so the second `read` returns an empty …

Add failing test which tries to save the same content twice

---

storages/backends/s3boto3.py

This is needed for Django 1.11 as we can no longer assume that the file we're looking is starting from the beginning, this can cause issues with empty files being saved instead of GZ variants.

Ensure that we're reading the file from the start

---

storages/backends/s3boto3.py

Matches [S3BotoStorage](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L355) and required for:
https://github.com/jazzband/collectfast/pull/108

Fix the mtime when gzipping in S3Boto3Storage

---

AUTHORS
storages/backends/dropbox.py
tests/test_dropbox.py

This PR:
- fixes a regression in `DropBoxStorage._save` introduced with e46f306 (see https://github.com/jschneier/django-storages/issues/378);
- adds large file support for Dropbox (see https://github.com/jschneier/django-storages/issues/301).
I've tested uploading a 1.5 GB file and it works fine.

Dropbox: large file support and a regression fix

---

storages/backends/s3boto.py
storages/backends/s3boto3.py
tests/test_s3boto.py
tests/test_s3boto3.py
tox.ini

Fallback on other content-type detection methods when the content_type property is None
Fixes #406

Detect Content-Type when content_type property is null

---

storages/backends/s3boto.py
storages/backends/s3boto3.py
tests/test_s3boto.py
tests/test_s3boto3.py

This is a consolidation of #197 and #365 with merge conflicts resolved and `flake8` niggles addressed. All credit for the fixes belongs to @vinayinvicible and @tommwatson. 
Since the data-corruption problem is long-standing and severe, please consider merging these fixes and their included unit tests. If there are any issues with the proposed changes that make you hesitate to merge, please bring them up candidly—I'll work to address them ASAP!
I believe that this PR should:
* Close #169
* Fix #160
* Fix #364
* Fix #449
Additionally, #450 is related but cannot be closed by this PR because it also addresses #383, which is a separate issue about file _reading_.

Fix data-corruption issue with s3boto and s3boto3 multipart uploads

---

storages/utils.py
tests/test_utils.py

Unused since its introduction in c8e902b4c9e95ada0aa12488e6fd26cfad47fe85. Never passed as `True`, always `False`.

Remove unused argument strict from utils.setting()

---

storages/backends/gcloud.py
storages/backends/gs.py
storages/backends/s3boto.py
storages/backends/s3boto3.py

The function is defined with `default=None`, no need pass a value.

Remove redundant argument None to setting()

---

CHANGELOG.rst
README.rst

Read the Docs moved to hosting at readthedocs.io instead of readthedocs.org. Fix all links in the project.
For additional details, see:
https://blog.readthedocs.com/securing-subdomains/

Prefer readthedocs.io instead of readthedocs.org for doc links

---

storages/backends/gcloud.py
storages/backends/s3boto.py
storages/backends/s3boto3.py
storages/utils.py
tests/test_gcloud.py
tests/test_gs.py
tests/test_s3boto.py
tests/test_s3boto3.py

If a setting is considered invalid, raise an exception instead of silently changing it to some other value. Avoids confusion and forces the library user to be explicit.
For example, setting S3 location to a value with a leading slash previously stripped it. Instead, now instruct the user to use a valid value without the leading slash.

Avoid silently changing settings; raise ImproperlyConfigured instead

---

storages/utils.py

Fix missing import needed in #520

Missing import in check_location

---

docs/backends/digital-ocean-spaces.rst

As requested. I've reformatted the text into the format of the other docs pages (I think) but please double check and let me know if there's any issues.

Add documentation for Digital Ocean Spaces

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

**Background**
As discussed in #381, the default setting of "public-read" for `AWS_DEFAULT_ACL` is insecure -- if a user sets up a bucket that is private by default, they should have to explicitly opt in for django-storages to override that choice and upload globally readable files. By default uploads should use the bucket's settings.
@jschneier suggested in that bug that the change should be made in django-storages 2.0, since it would be a breaking change for many users.
@robatwave commented that one can currently opt into the proposed behavior by setting `AWS_DEFAULT_ACL=None` explicitly. This does not work for me; with that setting I get `'NoneType' object has no attribute 'parts'` in `S3Boto3StorageFile.close`.
@ticosax sent a pull request last year, #429, that implements the breaking …

Warn about upcoming change to AWS_DEFAULT_ACL; allow None in AWS_DEFAULT_ACL

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Deprecated in favor of `default_acl` and `bucket_name`. Encourage users to upgrade so the deprecated versions can eventually be removed.

Deprecate old arguments acl & bucket to S3Boto3Storage

---

README.rst
docs/backends/gcloud.rst
docs/index.rst
tests/settings.py

django-storages is not required to be in `INSTALLED_APPS`. It provides no models, templates, templatetags, or other Django features that use a registered app. Can simplify the installation instructions and avoid unnecessary configuration.
The Django configuration used, `DEFAULT_FILE_STORAGE`, can be any valid Python path even if it isn't a configured app.
I have been successfully using django-storages without `INSTALLED_APPS` on projects for quite some time.

Simplify install instructions by removing INSTALLED_APPS step

---

.travis.yml

Upgrading pip, setuptools, and wheel is unnecessary. It only adds time and network traffic to the CI build.

Remove unnecessary install step from Travis CI

---

docs/backends/gcloud.rst
storages/backends/gcloud.py
tests/test_gcloud.py

For public files use blob.public_url. This does not require a network trip to Google, so much faster. 
For non-public files, it will return a signed url. The default authentication is set to 1 day but is configurable with GS_EXPIRES_IN. 
It relies on the GS_DEFAULT_ACL to tell if the files will be public. Actually, checking the ACL with Google would be slow. It does not use the GS_CREATE_BUCKET_ACL on purpose because public buckets are a bad idea and lead to a lot of security leaks. 
Docs + tests are updated.
Does not currently support a custom url (did not before either), can be added as an additional feature.
Fixes #491 and #425

Gcloud url fixes to handle public and private files 

---

storages/backends/s3boto.py
storages/backends/s3boto3.py

S3: Consistently use compresslevel=9 for gzipped content

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Use boto3 paginator to fetch results. Code based on django-s3-storage.
Fixes #95

Rewrite S3Boto3Storage.listdir() for efficiency

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Prevents warning spam to django-storages users that have overridden the insecure setting as a class variable.

Avoid AWS_DEFAULT_ACL warning when overridden as a class variable

---

docs/backends/amazon-S3.rst

While reviewing the docs, I found the reference to "extreme legacy
backend" confusing and ambiguous. It provides no details and doesn't
name what was removed. Diving into the git logs, I discovered this was
referencing a previous S3 backend, "storages.backends.s3.S3Storage". As
this was removed in 2014 and was part of the quite old 1.2 release, I
think enough time has passed such that this reference can be completely
removed.

Remove confusing sentence about legacy storage s3.S3Storage

---

tests/settings.py

Backend settings should be set as necessary in tests; not globally.

Remove unnecessary settings from tests/settings.py

---

storages/backends/apache_libcloud.py
storages/backends/ftp.py
storages/backends/s3boto.py
storages/backends/s3boto3.py
storages/backends/sftpstorage.py
tests/test_dropbox.py
tests/test_ftp.py
tests/test_sftp.py

`io.BytesIO` is available on all supported Pythons. No need to use six shim. Use future compatible interface.

Prefer io.BytesIO; available on all supported Pythons

---

CHANGELOG.rst

As spelled on https://pypi.org/.

Correct capitalization of PyPI

---

docs/conf.py

When building the docs, fixes the warning:
```
html_static_path entry '.../django-storages/docs/_static' does not exist
```

Remove Sphinx conf html_static_path to missing directory

---

docs/backends/azure.rst

This is just a typo which I found by copy-pasting from the docs.

Fix a typo in Azure docs

---

docs/backends/amazon-S3.rst

Copied from this location and spent half an hour to just figure out why the module not found error was there. Realized that the documentation missed out on the correct module name.

Fixing wrong documentation

---

.travis.yml
tox.ini

Django added Python 3.7 support to Django 1.11 in version 1.11.17.
https://docs.djangoproject.com/en/dev/releases/1.11.17/
> Django 1.11.17 ... adds compatibility with Python 3.7.

Add py37-django111 to the test matrix

---

.travis.yml
tox.ini

Django removed support for Python 3.5 in
https://github.com/django/django/commit/7e6b214ed34f5562dbd83cf54924a5b589a29715

Remove py35-djangomaster from the test matrix

---

README.rst

When I first started using the package it took me a while to know I had to remove the `storage` parameter on my models FileFields to make this library work. I believe it would be nice to clarify that straight on the readme file. Like me, it will same some peeps time :)

Updated README to clarify information on the models needed configuration.

---

storages/backends/gcloud.py
tests/test_gcloud.py

There is no need to make a separate call to set ACLs on a file (blob). ACLs can be passed as a parameter to the "upload_from_file" function.
On a side note, the reason I started looking at this code is that over the last few days I started getting errors when uploading files to Google cloud: "503 GET https://www.googleapis.com/storage/v1/b/BUCKET_NAME/o/FILE_PATH/acl: Backend Error"
I don't have a clear explanation on why this was happening, I am guessing that setting ACLs right after the file was uploaded may have caused some contention issues on Google side. (the issue was totally random)
With the change proposed in this PR I don't see any more issues when uploading files.

Google Storage Backend: settings ACLs when file is uploaded

---

docs/backends/amazon-S3.rst

Document the AWS IAM policy permissions which are required for the most
common use cases of the AWS S3 backend.
Fixes Issue: https://github.com/jschneier/django-storages/issues/685

Document AWS IAM policy permissions for AWS S3 backend

---

AUTHORS
storages/backends/dropbox.py
tests/test_dropbox.py

This not only fixes #713, #714, #620, #396 and #397 but restores the functionality of the backed for the current Dropbox client (9.3 - supersedes #402)

Update Dropbox backend for dropbox==9.3.0 client

---

storages/backends/azure_storage.py
tests/test_azure.py

Hello,
Microsoft adds new parameters to its function generate_blob_shared_access_signature (to see more details: [Azure storage python issue 595](https://github.com/Azure/azure-storage-python/issues/595))
Without the permission parameter in generate_blob_shared_access_signature, the URL generated by Azure sdk is incorrect and we have the following error : `sp is mandatory. cannot be empty`
This PR should correct this and fix #705

Azure: Adds missing parameter sp (permission) to Azure signature

---

docs/backends/amazon-S3.rst

Tested in region `cn-northwest-1` with Django 2.2.1, django-storage 1.7.1 and boto3 1.9.166, `AWS_S3_REGION_NAME` setting is still needed even with `AWS_S3_ENDPOINT_URL`. Otherwise, you may come across the `AuthorizationQueryParametersError` with example message _Error parsing the X-Amz-Credential parameter; the region 'ap-southeast-1' is wrong; expecting 'cn-northwest-1'_.

AWS_S3_REGION_NAME is still needed

---

storages/backends/sftpstorage.py

Default Django implementation uses os.path.exists and open(), which is wrong.

SFTPStorage: Fix reopen file

---

.travis.yml
setup.py
tox.ini

Announcement: https://www.djangoproject.com/weblog/2019/apr/01/django-22-released/
Release notes: https://docs.djangoproject.com/en/2.2/releases/2.2/
Django master dropped support for Python 3.5.

Test against for Django 2.2 release

---

docs/backends/dropbox.rst
storages/backends/dropbox.py

Dropbox: add configurable timeout and improve docs

---

storages/backends/gcloud.py
tests/test_gcloud.py

Motivation for this change is to send fewer requests to Google Storage
API. We do not check existence of bucket unless auto_create_bucket is
configured or exists('') is called.
When creating bucket, instead of making two requests to get and create,
we just create and look for conflict.
Based on the work in #575 and supersedes #412.

Google: Only verify bucket if auto_create is True

---

docs/backends/azure.rst
storages/backends/azure_storage.py
tests/integration/test_azure.py
tests/test_azure.py

Non messed up rebased version of #658.
Closes #643. 
Closes #656.

Azure: Support all blobstorage settings

---

storages/backends/azure_storage.py
tests/integration/test_azure.py
tests/test_azure.py

fixes #609
Changes:
* remove stripping special characters from file name
* escape URL reserved and unsafe characters on `url` method
Notes:
* This is consistent with the other storages
* Django does the same name cleaning as the previous code, anyway
* Django name cleaning can be bypassed by overriding `get_valid_name` or calling `default_storage.save` directly. This was not possible with the old code
* Since this is a superset of what was previously allowed, it's a minor breaking change
* Files uploaded with the previous code will still work
CC @jschneier

Fix Azure name cleanup

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

This commit fixed a [bug in Django](https://code.djangoproject.com/ticket/26495) that was addressed in the 1.10 release. It then had the knock on effects of causing #382. Since this library only supports 1.11+ this can be safely reverted. 
This reverts commit c73680e7d7f906b841f77dd1aa4f5c3cfa8fb3a2.
Closes #382.

S3Boto3: Fix ValueError I/O operation on closed file

---

storages/backends/gcloud.py
tests/test_gcloud.py

GoogleCloud: Set predefined_acl when using file write operations

---

storages/backends/apache_libcloud.py
storages/backends/ftp.py
storages/backends/s3boto3.py
storages/backends/sftpstorage.py
tests/test_s3boto.py
tests/test_s3boto3.py

I fixed #758.
If django-storages ends support for Python2, close this.

Added error handling at import django.utils.six module. #758

---

setup.py

This is a temporary fix for #784

Pin dependency of azure storage blob to revert breakage by version 12

---

storages/backends/s3boto3.py

S3Boto3: Include error message when reraising

---

docs/backends/azure.rst
storages/backends/azure_storage.py
tests/test_azure.py

The HTTP header value can be controlled via the AZURE_CACHE_CONTROL environment variable.
For example: AZURE_CACHE_CONTROL="public, max-age=31536000"
Issues #323 and #674.

Added Cache-Control header support for Azure backend

---

AUTHORS
docs/backends/gcloud.rst
setup.py
storages/backends/gcloud.py
tests/test_gcloud.py

Add new `GS_CUSTOM_ENDPOINT` setting to allow usage of custom domains/URLs with Google Cloud Storage, similar to `AWS_S3_CUSTOM_DOMAIN`.

Allow custom endpoints with Google Cloud Storage.

---

storages/backends/dropbox.py
tests/test_dropbox.py

Use an empty string instead of `/` in `DropBoxStorage.listdir`
Fix #761 Dropbox base path / should be an empty string
It solves this kind of issues:
```
Traceback (most recent call last):
File "manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute …
```

[dropbox] Fix crash on DropBoxStorage.listdir

---

.travis.yml

Since May 2019, Travis has used Ubuntu Xenial 16.04 as the default
Travis CI build environment.
For additional details, see:
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

Remove default 'dist: xenial' from Travis CI configuration

---

.travis.yml
setup.py
tox.ini

Python 3.8 was released on October 14th, 2019.

Add Python 3.8 to the test matrix

---

tox.ini

The pytest project recommends using the command pytest as an entry
point, not py.test.
https://docs.pytest.org/en/latest/faq.html#why-can-i-use-both-pytest-and-py-test-commands
> Why can I use both pytest and py.test commands?
>
> pytest used to be part of the py package, which provided several
> developer utilities, all starting with py.<TAB>, thus providing nice
> TAB-completion. If you install pip install pycmd you get these tools
> from a separate package. Once pytest became a separate package, the
> py.test name was retained due to avoid a naming conflict with another
> tool. This conflict was eventually resolved, and the pytest command
> was therefore introduced. In future versions of pytest, we may
> deprecate and later remove the py.test command to avoid perpetuating
> the …

Replace deprecated py.test command with pytest

---

AUTHORS
docs/backends/amazon-S3.rst
storages/backends/s3boto3.py
tests/test_s3boto3.py

This PR adds functionality to `S3Boto3StorageFile` that will create an empty file if no bytes are written to S3 after opening a file in `w` mode, similar to how `FileSystemStorage` and Python's native `open` work.
Let me know if I'm missing anything or if you have any questions. Thank you!
Fixes https://github.com/jschneier/django-storages/issues/435

Create empty file if no bytes written to S3 file in 'w' mode

---

docs/backends/ftp.rst
storages/backends/ftp.py

Please add utf-8 support for ftp storage .

Added utf-8 support for ftp storage

---

AUTHORS
storages/backends/sftpstorage.py

This PR ensure that SFTPStorage raises an exception that can be handled, rather than simply printing a message to stdout (Issue #835).

Allow SFTPStorage to raise exceptions upon connection error

---

docs/backends/gcloud.rst

Hello, thanks for this amazing project.
I just wanted to add a small note to the docs. 
I spent a few hours trying to figure this out, so I thought this would help others who might have set Uniform access control on their bucket.

Add note about not being able to use Uniform access control on google cloud bucket

---

AUTHORS
storages/backends/s3boto3.py
tests/test_s3boto3.py

I went ahead and wrote a proposal for #853.
Allow to pass `http_method` to `storage.url` in order to calculate the signature accordingly. By default, it uses ~~'GET'~~ `None` to keep backward compatibility.
Please, let me know if this makes sense to you and suggest any changes you consider appropriate.

Add S3 support for `http_method` in `storage.url`

---

storages/backends/azure_storage.py
storages/backends/gcloud.py
storages/backends/s3boto3.py
storages/base.py
tests/test_azure.py
tests/test_gcloud.py
tests/test_s3boto3.py

Makes the storage classes usable with Django's `override_settings`. For example, projects can now change the S3 location & bucket when running their tests. Affects the following backends:
- azure_storage
- gcloud
- gs
- s3boto
- s3boto3
The remaining storage backends do not need to be altered as they do no calculate settings at import time.
The class `BaseStorage` was created to use a common pattern to initialize settings for various backends. Users of these backends can expect them to work consistently. This class is fully backwards compatible. Settings can now be set:
- In settings.py
- Using override_settings
- As a class variable
- As an argument to __init__
Closes #498
Completes all necessary backends and adds tests.

Calculate settings when storage is instantiated; not imported

---

storages/backends/gcloud.py

Assigning the settings is already handled by the BaseStorage class.
Mistakenly left in as part of 955ee63b31c5f3e053fd5461c7c6dec06d2911af
due to a bad rebase.

Remove duplicate settings assignment in glcoud backend

---

storages/base.py

Based on my comment https://github.com/jschneier/django-storages/pull/524#issuecomment-600760753
> I'm not sure an empty {} is warranted because it's likely that a storage is providing some options, and it should use the get_default_settings for that? Or do you suspect people would create a new storage based off the BaseStorage that would have no settings? I guess for maybe a private source/single use storage that might be the case.
@jdufresne not sure if you had seen my subsequent comment (linked), but figured I could create a PR to discuss.

add default implementation of get_default_settings to BaseStorage

---

AUTHORS
docs/backends/amazon-S3.rst

1. Fix 'Missing required field Principal' error of IAM policy permissions.
2. Update AUTHORS

Update amazon-S3.rst to fix "Missing required field Principal" error

---

AUTHORS
docs/backends/dropbox.rst
storages/backends/dropbox.py

Adding the possibility to overwrite existing files at Dropbox instead of allowing Django change it's name.

Write mode option for Dropbox

---

storages/backends/gcloud.py

Create `blob_chunk_size` as a `GoogleCloudStorage` attribute so that it's easy to override `GS_BLOB_CHUNK_SIZE` in custom Google Cloud storage backends. Without this change, you have to create a new `GoogleCloudFile` and copy a lot of code to make it work

Add blob_chunk_size to get_default_settings of GoogleCloudStorage

---

AUTHORS
storages/backends/sftpstorage.py
tests/test_sftp.py

This PR makes the SFTPStorage class configurable via class variables (similar to other backends). That way subclassing is more convenient. (#851).
As far as I can tell, these changes are backwards compatible.

Allow SFTPStorage to be configured via class variables

---

.travis.yml
setup.cfg
tox.ini

These versions are not recommended for production. They are no longer
receiving bug fixes, including for security issues.
Django 2.0 went EOL April 1, 2019.
Django 2.1 went EOL December 2, 2019.
For a complete list of supported Django versions, see:
https://www.djangoproject.com/download/#supported-versions
Removing testing of these EOL versions greatly reduces testing time and
resources.

Remove testing for end-of-life Django versions

---

storages/backends/s3boto3.py
tests/test_s3boto3.py
tox.ini

Fixes #456. Similar to #484 but uses AWS CloudFront signed URLS ([See AWS docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html))
This is probably the right way to approach the problem in #484, but if that solution works that might be an alternative (not sure how @mattjegan configured S3+CloundFront)

[s3] Add support for signing CloudFront URLs

---

storages/backends/ftp.py
tests/test_ftp.py

The function _mkremdirs in FTPStorage just consider a simple subdirectories with 2 nested paths.
With this fix subdirectories 2+ nested paths creation.

Fix FTP multiple nested paths

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

At the moment, all URLs are being signed, even if `querystring_auth` is set to `False`.
This is needed in a scenario when a user have a mix of private and public content distributed via CloudFront and they don't want to sign public urls.
Updated tests to cover the scenario.

Sign CloudFront urls only in case querystring_auth is enabled

---

CHANGELOG.rst
docs/backends/amazon-S3.rst
storages/backends/s3boto3.py
tests/test_s3boto3.py

The ACL deprecation warnings produced by S3BotoStorage can be a false positives and create _a lot_ of noise. I suggest the project move forward with removing these features as scheduled. Dropping the
deprecated behavior now means:
- The minimum supported version of boto3 is now 1.4.4.
- The `S3Boto3Storage` backend no longer accepts the argument `acl`. Use the `ACL` key in `AWS_S3_OBJECT_PARAMETERS` instead.
- The `S3Boto3Storage` backend no longer accepts the argument `bucket`. Use `bucket_name` or the setting `AWS_STORAGE_BUCKET_NAME` instead.
- The `S3Boto3Storage` backend no longer automatically creates the bucket. Doing so had encouraged using overly broad credentials. As a result, the `AWS_BUCKET_ACL` setting has been removed.
- The `S3Boto3Storage` backend no longer not longer …

Clean up deprecated behaviors from the S3BotoStorage

---

.travis.yml
CHANGELOG.rst
setup.cfg
tox.ini

Django 1.11 went end of life April 1, 2020. It is no longer receiving
bug fixes, including for security issues.
Removing support will reduce testing time and resources.
For more details on supported Django versions, see:
https://www.djangoproject.com/download/

Remove support for end-of-life Django 1.11

---

CHANGELOG.rst
docs/backends/gcloud.rst
storages/backends/gcloud.py
tests/test_gcloud.py

The removal was targeted for the 1.10 release. Best to include in the
existing batch of removed deprecated behaviors.

Remove deprecated GS_AUTO_CREATE_BUCKET

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Fixed typo in `S3Boto3StorageFile.__init__()` that prevented files opened in "r" mode from being read.
lambda has a higher precedence than if-else, so `self._force_mode` was set to a function that returned
another lambda when `'b'` is not in `mode`.
Also added regression test.

Fixed typo in S3Boto3StorageFile.__init__()

---

docs/backends/gcloud.rst

* use integrated auth, either by default or dedicated service account
* otherwise, use local creds file from said service account
Also expands on types of compute options.

Update gcloud backend authentication strategy

---

tox.ini

Per the Python documentation, there is no "all" filter. It looks like
"always" was intended:
https://docs.python.org/3/library/warnings.html#the-warnings-filter
The filter "all" happens to work as it is an undocumented alias, but
might as well used the documented name.
https://github.com/python/cpython/blob/v3.8.2/Lib/warnings.py#L244

Correct name of warning filter "all" → "always"

---

docs/backends/amazon-S3.rst
docs/backends/azure.rst
docs/backends/gcloud.rst

Many editors clean up trailing white space on save. By removing it all
in one go, it helps keep future diffs cleaner by avoiding spurious white
space changes on unrelated lines.

Trim trailing white space throughout the project

---

storages/backends/sftpstorage.py
tests/test_sftp.py

This allows the SFTP_STORAGE_HOST setting to actually be used.
In the current implementation, the host=None in init causes the host attribute on SFTPStorage to always revert to None if using the DEFAULT_FILE_STORAGE setting in Django. Removing the default value for host in the init signature allows the default parameter from SFTP_STORAGE_HOST to be applied.

Remove host parameter as obligatory in SFTPStorage

---

docs/backends/amazon-S3.rst
storages/backends/s3boto3.py
tests/test_s3boto3.py

This restores `AWS_DEFAULT_ACL` handling. It was too aggressive to remove it.

[s3] Restore AWS_DEFAULT_ACL handling

---

docs/backends/ftp.rst

Fix a wrong setting (`FTP_STORAGE_LOCATION` instead of `LOCATION`).

docs: Fix documentation for FtpStorage backend

---

docs/backends/amazon-S3.rst

Documentation on S3 is missing `from django.core.files.base import ContentFile` import here:

docs: Add missing import for S3 backend

---

docs/backends/gcloud.rst
storages/backends/gcloud.py

Rebased version of existing PR by @dulacp in #910 that fixes merge conflict and should pass CI tests.
As per docs in #910 
>  To support Uniform permissions buckets on Google Cloud Storage, we need to keep GS_DEFAULT_ACL to None, but it forces each url to be signed, which is useless since the uniform permission is usually meant to give world read access. This new parameter solves this use case reported in #783, #846 and #909.

Add setting to disable signed URLs for GCS uniform buckets

---

storages/backends/s3boto3.py

This allows the `storages.backends.s3boto3` module to be cleanly imported before Django settings are configured. This further supports the changes from #524.
Removing `S3Boto3StorageFile.buffer_size` as a class variable does not affect the API surface of `S3Boto3StorageFile`, as `buffer_size` was always accessible as an instance variable.

Calculate settings for S3Boto3StorageFile when instantiated, not imported

---

storages/backends/s3boto3.py
storages/utils.py
tests/test_s3boto3.py

S3: Workaround boto bug to fix collectstatic issue

---

docs/backends/azure.rst
storages/backends/azure_storage.py

[azure] Add method to set ContentDisposition

---

storages/backends/s3boto3.py
storages/utils.py
tests/test_s3boto3.py

[s3] Fix writing bytearray content

---

docs/backends/amazon-S3.rst
storages/backends/s3boto3.py
storages/utils.py
tests/test_s3boto3.py

Fix collectstatic manifest file handling & revert #955

---

docs/backends/azure.rst

I added all the possible parameters for `AZURE_OBJECT_PARAMETERS`, similar to the [S3 documentation](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) with the `AWS_S3_OBJECT_PARAMETERS` setting. Since there's a fairly small number of parameters I just mentioned all of them.

Docs: Specify the allowed parameters for AZURE_OBJECT_PARAMETERS

---

storages/backends/s3boto3.py

When django-storages is used from an app which is configured by env variables
fed into dynaconf (or probably other situations), it's not easy to directly
coerce a string representation of the signing key into a bytes-like object; it
comes in as a string.  This detects that situation and encodes the string.

Convert string to bytes if needed

---

.travis.yml
tests/test_azure.py

Improves the state of the travis build, removing ~~some~~ all of the red.
* the default `xenial` distro for travis is ancient; upgrading to Ubuntu Focal gave us a better `pip`, which installs `cryptography` from a wheel instead of building from source. Building from source was failing because `rustc` wasn't installed. But also it was slow; installing from a wheel is much faster.
* the azure test had been failing [since May's django security releases](https://docs.djangoproject.com/en/3.2/releases/2.2.21/#cve-2021-31542-potential-directory-traversal-via-uploaded-files), so I fixed the test to expect the new behaviour going forward.

Fix all the Travis CI failures

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

S3 returns the ETag for each part of the upload while we're PUTting
them. However, until now we were ignoring those responses, and instead
doing a separate ListParts (GET) request for the upload object, just
before POSTing the list of parts to the completion endpoint to finalise
the upload.
That extra GET request is unnecessary so this commit removes it.

S3: Avoid a ListParts request in multipart upload

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

S3Boto3Storage with custom domain now accepts url parameters

---

AUTHORS
docs/backends/amazon-S3.rst
storages/backends/s3boto3.py
tests/test_s3boto3.py

This uses the setting AWS_S3_SESSION_PROFILE as an alternative to using static credentials in AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.  
This addresses the spirit of https://github.com/jschneier/django-storages/issues/774 and implements the suggestion in https://github.com/jschneier/django-storages/issues/895

Allow the use of AWS profiles for S3 access

---

storages/backends/dropbox.py

Proposed additional input validation from settings.py otherwise wrong values produce cryptic error:
```
File "/app/.heroku/python/lib/python3.7/site-packages/stone/backends/python_rsrc/stone_base.py", line 141, in __init__
assert validator is not None, 'Invalid tag %r.' % tag
AssertionError: Invalid tag True.
```
found and explained here: https://stackoverflow.com/questions/67872466/error-when-uploading-viewing-certain-pictures-rendition-not-found-django-sto

Add more input validation to dropbox.py

---

README.rst

This replaces the one for travis-ci which is no longer used.

In README.rst add build status badge for github actions CI

---

storages/backends/s3boto3.py

This change:
b13efd9
swapped from using `self.access_key_names` to `S3Boto3Storage.access_key_names`; it's unclear if that was intentional or not, but that means it does not accept overrides; we relied on overrides to use some bucket specific keys provided by rook ceph.

Re-allow overrides of access_key_names

---

docs/backends/amazon-S3.rst

There is a typo in the documentation which incorrectly states `AWS_S3_SECRET_KEY_ID` instead of `AWS_S3_SECRET_ACCESS_KEY` as the proper settings configuration.

Fix typo in S3Boto3Storage documentation

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

* Move the seek to happen before compression instead of after
* Only seek if content.seekable() is true
Fixes issue #860.

Support saving file objects that aren't seekable in S3Boto3Storage

---

storages/backends/gcloud.py

fix for #998
Add exception handling for `delete_blob` for gcloud backend.
I does not raise a 404 NotFound, if the blob to be deleted not exists. This is consistent how Azure and S3 backends handle this case.

[gcloud] do not raise exception when trying to delete a non existing blob

---

docs/backends/gcloud.rst
storages/backends/gcloud.py

[gcloud] Add configurable blob parameters

---

setup.cfg
storages/backends/gcloud.py
tests/test_gcloud.py

Update URL signing version from v2 to v4. Increase minimum google-cloud-storage library version so that custom endpoints work
properly.
This supersedes #837 - moving to v4 signed URLs and using `bucket_bound_hostname` will fix the bug with invalid signed URLs being generated without having to resort to the hackish solution used in that pull request.

GoogleCloud: Use V4 signed URLs

---

storages/backends/s3boto3.py

I'm trying to determine why I'm seeing some files overwriting other files when they have the same name.
I feel like this might be the source of the issue (perhaps due to previous code catching a network error or some other error) but I don't quite have the depth of knowledge to validate that.
Does this suggested change look like it might address a bug?

Check for `NoSuchKey` error response in `exists()`

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

[s3] Re-raise non-404 errors in .exists()

---

storages/backends/sftpstorage.py
tests/test_sftp.py

This was covering up socket.timeout exceptions.
Fixes #1064.

[sftp] Catch FileNotFoundError rather than OSError in .exists()

---

tests/test_azure.py

Preparing things for future Django releases.
According to https://docs.djangoproject.com/en/dev/releases/4.0/#use-of-pytz-time-zones pytz will be deprecated.

Remove pytz dependency

---

storages/backends/azure_storage.py

For some reason, support for AZURE_ENDPOINT_SUFFIX was dropped in 1.12. Adding this feature back to support Azure.cn storage accounts.

added support for endpoint_suffix

---

storages/backends/azure_storage.py

`StorageStreamDownloader.download_to_stream()` is [deprecated](https://github.com/Azure/azure-sdk-for-python/blob/ce738fc2b1ac826238a6b09352fb2444ce7a3a53/sdk/storage/azure-storage-blob/azure/storage/blob/_download.py#L631) (and `max_concurrency` already defaults to 1)

Azure `download_to_stream()` is deprecated

---

AUTHORS
storages/backends/s3boto3.py
tests/test_s3boto3.py

- When using gevent, s3 operations were breaking if using threading. Allow to disable it adding AWS_S3_USE_THREADS configuration flag
- Closes #1110

Add `AWS_S3_USE_THREADS` configuration variable

---

storages/backends/azure_storage.py
tests/test_azure.py

Fixes #1131 
fix is basically as suggested, but I've formatted it for consistency with https://github.com/jschneier/django-storages/blob/0ceb9e03b89a00395cad9bd5ce3909cf99221cd1/storages/backends/azure_storage.py#L253-L256

[azure] fix get_modified_time()

---

storages/backends/dropbox.py

This PR fixes https://github.com/jschneier/django-storages/issues/1157 by silencing `ApiError` in the Dropbox the `url()` function.

Ignore ApiError exception in url()

---

AUTHORS
docs/backends/dropbox.rst
storages/backends/dropbox.py
tests/test_dropbox.py

This PR adds `DROPBOX_APP_KEY`, `DROPBOX_APP_SECRET` and `DROPBOX_OAUTH2_REFRESH_TOKEN` settings.
The PR addresses https://github.com/jschneier/django-storages/issues/1018, https://github.com/jschneier/django-storages/issues/993.

Add refresh token support

---

README.rst
docs/conf.py

There are small typos in:
- README.rst
- docs/conf.py
Fixes:
- Should read `that` rather than `shat`.
- Should read `commercial` rather than `commerical`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

docs/backends/amazon-S3.rst
storages/backends/s3boto3.py

Remove AWS_S3_SECURE_URLS setting
Update AWS_S3_URL_PROTOCOL setting to default to https:
Document AWS_S3_URL_PROTOCOL
Resolves #1126, #1150

[s3] update secure url creation handling

---

storages/backends/gcloud.py
tests/test_gcloud.py

Use a default retry policy when uploading a file to Google Storage.

gcloud: Use DEFAULT_RETRY when uploading a file.

---

docs/backends/azure.rst
storages/backends/azure_storage.py
tests/test_azure.py

Fixes #1116, #1097
This restores the previous behaviour that was in 1.11 (with old Azure backend) so that the custom domain is used only for retrieving the blob URLs. All other operations like uploads go through the actual storage account URL. I updated the docs to clarify this too.
In 1.12, we switched to the new storage SDK and also changed it so that all storage operations go through the custom domain instead (not sure if intentional or not). Doing so uncovered several upstream issues that affect storage operations when connecting directly to the custom domain. More details in #1116.
I also made a small change to simplify the `exists()` method a bit.

[azure] Use `AZURE_CUSTOM_DOMAIN` only for retrieving blob URLs, and use storage URL for other operations

---

storages/backends/gcloud.py

It enables using kwargs, such as `content_type` https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_generate_signed_url
Ref: https://github.com/jschneier/django-storages/pull/1071

Add GCloud parameters as kwargs for storage.url

---

setup.cfg
storages/backends/gcloud.py
storages/backends/s3boto3.py
storages/backends/sftpstorage.py
storages/utils.py
tests/test_sftp.py

* Move seekability test to a separate helper function
* Stop calling content.open() from SFTPStorage._save
* Require at least version 1.10.0 of paramiko
* Use SFTPClient.putfo() in SFTPStorage._save()
This produces a fairly major difference in performance, the original version needs over 10x the time it takes for the modified version to transfer a 380M test file. Transferring said file with the current version also requires about 2 gigabytes of memory, which drops to 50 megabytes after the change.

Improve SFTPStorage

---

storages/utils.py
tests/test_utils.py

[general] add support for pathlib.Path to clean_name

---

docs/backends/backblaze-B2.rst

Backblaze B2 is a widely used, S3-compatible cloud object storage service. After [answering a question on using B2 with django-storages on Reddit](https://www.reddit.com/r/backblaze/comments/sdb2m7/comment/hud0r20/?utm_source=share&utm_medium=web2x&context=3), I figured I'd drop the same information here.

Added instructions to use S3 backend with Backblaze B2

---

docs/backends/gcloud.rst

[docs/gcloud] add caveat about maximum value of GS_EXPIRATION in v4

---

storages/backends/azure_storage.py

Please review the changes related to this issue, I have only updated the changes related to url functionality in AzureStorage.
I have tested by importing the module into my django application, haven't used test cases as they were not using connection_string.
Please let me know if they are any improvements/changes required.

fixes issue:1216

---

README.rst
docs/backends/amazon-S3.rst
docs/backends/apache_libcloud.rst
docs/backends/azure.rst
docs/backends/dropbox.rst
docs/backends/ftp.rst
docs/backends/gcloud.rst

Changed anything like
```python
STORAGES = {"default": "storages.backends.gcloud.GoogleCloudStorage"}
```
to
```python
STORAGES = {"default": {"BACKEND": "storages.backends.gcloud.GoogleCloudStorage"}}
```
And added a bit to the README about the settings for Django >= 4.2 (not sure if the wording is how you would do it, so obviously feel free to change it!).
For #1207

Fix STORAGES settings in docs for Django 4.2

---

storages/backends/s3boto3.py

Without this line, `BaseStorage.__init__` raises an `ImproperlyConfigured` exception which prevents passing security_token as a parameter to `S3Boto3Storage.__init__`.
We use django-storages to manage a multi-tenant / multi-S3-bucket / multi-aws-account service. As a result, multiple `S3Boto3Storage` classes get instantiated with the proper information (access_key, secret_key and security_token).
This line fixes our problem. I am not sure if there was a reason why `security_token` is not
listed in default settings and/or if as a result it breaks some other use cases.

enables passing `security_token` to constructor

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

Currently it appears that `S3Boto3StorageFile` uses the `closed` property defined by `FileProxyMixin`, which checks the condition `not self.file or self.file.closed` ([source](https://github.com/django/django/blob/main/django/core/files/utils.py#L54)). Since `self.file` in `S3Boto3StorageFile` is a property that delegates to `_get_file`, this check reopens the file. Thus `closed` always returns `False`.

check if underlying file object is closed in closed method

---

docs/backends/sftp.rst
setup.cfg
storages/backends/sftpstorage.py
tests/test_sftp.py

Closes #1234 by making the SFTP storage close the underlying SSH connection after being used as a context manager.
This is done by adding Paramiko's convenient `ClosingContextManager` to the SFTP storage and implementing its hook for closing. I could have implemented the context manager manually, but Paramiko is required for SFTP, anyway.
In doing so, this bumps the minimum Paramiko version from 1.10.0 to 1.15.0, which is the version that [introduced `ClosingContextManager`](https://github.com/paramiko/paramiko/commit/979838040f9ff2f52e369812be87f0c7c9c1a0db) almost 9 years ago.

Close SSH connection of SFTP storage

---

storages/backends/dropbox.py
tests/test_dropbox.py

[dropbox] fix name mangling by replacing lstrip with removeprefix

---

storages/backends/s3boto3.py

Add support for setting "cloudfront_key_id" and "cloudfront_key" through OPTIONS
Addresses issue #1271

S3Boto3Storage: add support for Cloudfront settings through OPTIONS

---

storages/backends/s3boto3.py
tests/test_s3boto3.py

S3Boto3StorageFile respects mode on readlines

---

.github/workflows/ci.yml
ruff.toml
setup.cfg
storages/backends/ftp.py
storages/backends/s3.py
storages/utils.py
tests/test_s3.py
tox.ini

[Ruff](https://beta.ruff.rs/) supports [over 600 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.

Lint Python code with ruff instead of flake8 and isort

---

storages/backends/s3.py
tests/test_s3.py

As of now, attempting to get the file size from `S3Storage` always raises a `botocore.ClientError`, which is vague and may not fall under existing file-management related error handling.
Since may other methods in S3 storage already implement this kind of logic I have put the same in the `S3Storage.size` method. Now if the S3 error is a "not found" a more explanatory `FileNotFoundError` is raised instead.

Raise not exists error when attempting to get size for unexisting S3 file

---

storages/backends/s3.py
tests/test_s3.py

[s3] fix tracking S3File.closed

---

storages/backends/azure_storage.py
tests/test_azure.py

[azure] do not require both Account(Name|Key) in connection_string

---

storages/backends/s3.py
tests/test_s3.py

Moved the validation in `get_default_settings` to be inside `__init__` and check the final instantiated values, not just the values from settings. So even if the values in settings are incorrect, you can still create a S3 class by passing in the right values.

Move S3 auth & cloudfront_signer config validation to init

---

storages/backends/s3.py
tests/test_s3.py

[s3] raise ImproperlyConfigured if no bucket name is set

---

pyproject.toml

this project directly imports from azure-core, and should express that dependency.  1.13.0 is the version that introduced `azure.core.utils.parse_connection_string`
this is pedantry really, because azure-storage-blob already pulls azure-core as a sub-dependency

add explicit dependency on azure-core

---

storages/backends/s3.py
tests/test_s3.py

This reverts commit 9eeb8c3dbc8874fe01532ccaa09700362805922c.
See the discussion on the PR for people who are seeing issues in CI and testing.

Revert "[s3] raise ImproperlyConfigured if no bucket name is set (#1313)

---

storages/backends/s3.py
tests/test_s3.py

[s3] fix file reopening

---

storages/backends/gcloud.py

Replaces `GS_OBJECT_PARAMETRS` with `GS_OBJECT_PARAMETERS`.

Fix typo in code comment

---

docs/backends/amazon-S3.rst
storages/backends/s3.py
tests/test_s3.py

This change fixes disabling cloudfront signing by specifying "None" (or another falsy value). This allows multiple storage configs that are all distributed via cloudfront, but only some of the configs need to be signed.
x-ref: https://github.com/jschneier/django-storages/pull/1302

[s3] fix disabling cloudfront signing with cloudfront_signer=None

---

storages/backends/ftp.py
tests/test_ftp.py

I'm a Software Security Engineer from OpenRefactory-Inc. We are working with OpenSSF on [Project Alpha-Omega](https://alpha-omega.dev/). While triaging your project, our bug fixing tool generated the following message-
> In file: [ftp.py](https://github.com/jschneier/django-storages/blob/master/storages/backends/ftp.py#L87), method: _start_connection, a clear-text protocol such as FTP, Telnet or SMTP is used. These protocols [transfer data without any encryption,](https://cwe.mitre.org/data/definitions/319.html) which expose applications to a large range of risks. iCR suggested that data should be transferred over only secure transport channels.
As a result, I've added the support for `FTP_TLS` from `ftplib` library into the codebase. 
I copied the `test_ftp.py` file and modified it for …

Feature: Added support for FTP_TLS (Weak Cryptography Issue)

---

storages/backends/s3.py
tests/test_s3.py

This change fixes setting ``cloudfront_signer=None`` as a class variable to disable cloudfront signing (or passing a custom implementation), and is a follow up to https://github.com/jschneier/django-storages/pull/1326

[s3] fix disabling cloudfront signing with class variable

---

storages/backends/s3.py
storages/utils.py
tests/test_s3.py

Fix `AWS_S3_*` environment variables lookup

---

tox.ini

Pin moto dependency due to breaking changes

---

docs/backends/sftp.rst
storages/backends/sftpstorage.py

This PR adds SFTP_BASE_URL so that it can be used alongside other kinds of storages.

SFTP_BASE_URL

---

docs/backends/azure.rst

This PR explains how to use Azurite, the free local storage emulator for Azure Storage.
It also closes #1306

Explain how to use with Azurite (Azure Storage Emulator)

---

docs/backends/azure.rst

Managed Identity is the recommended approach for authenticating to Azure Storage Accounts from a Python app running on Azure (or when debugging in VS Code).
This extension already supports it, this PR gives an example of how to do it.

Add documentation on how to use Managed Identity (password-less auth) with Azure Storage

---

docs/backends/amazon-S3.rst
docs/backends/azure.rst
docs/backends/dropbox.rst
docs/backends/gcloud.rst
storages/backends/azure_storage.py
storages/backends/dropbox.py
storages/backends/gcloud.py
storages/backends/s3.py

Leaving `0` as the default means the file never gets rolled over to disk, resulting in higher memory usage than expected (or needed).
S3 and GCS both used `0` for their default value. Now, they use `FILE_UPLOAD_MAX_MEMORY_SIZE` (2.5MB by default). This is significantly better than `0`, but still allows configuration as needed.
Azure already set a default of 2MB, which is better, but now brought in line with S3 and GCS. Dropbox previously didn't allow configuration, so an additional setting was added.

Set a default size when using `SpooledTemporaryFile`

---

docs/backends/s3_compatible/cloudflare-r2.rst
docs/backends/s3_compatible/index.rst

[docs/r2] Create R2 docs

---

tox.ini

If you set up a different config file locally and then run tests, the tests easily fail, and who knows what it's doing with user's credentials :/

Don't look at user's AWS config when running tests

---

storages/backends/sftpstorage.py
tests/test_sftp.py

This pull request should fix #1363 and the recursion problem mentioned in the issue. 
The problem was related to the fact that the `.exists(self, name)` function assumes that the input is the `name` and not the full path. However, in `._save()` and `._mkdir()` a full path instead of the name was passed to the `.exists()`. 
To not interfere with the interface of the `.exists()` function, I introduced a `._exists(self, path)` function that uses the full path instead of the name as input.
I am aware that this is sort of a duplicate to what PR #1364 targets but I also wanted to "throw this solution into the ring" ;).

[sftp] Check full path for existance in ._save() and ._mkdir()

---

docs/backends/amazon-S3.rst
storages/backends/s3.py
tests/test_s3.py

[s3] Add ``client_config`` configuration setting

---

storages/backends/s3.py

Fixes https://github.com/jschneier/django-storages/pull/1381 CI Failures for Python 3.11 and above
`SpooledTemporaryFile` introduced new changes in 3.11 (https://docs.python.org/3/library/tempfile.html)
It now fully implements the `io.BufferedIOBase` and `io.TextIOBase` abstract base classes allowing the file
to be readable in the mode that it was specified (without accessing the underlying `._file` object). 
It seems like wrapping the underlying `._file` is forbidden for versions 3.11 and higher (results in the `ValueError`)
Having two have separate methods for different versions isn't the prettiest fix but should suffice.

[s3] Fix newlines test for python 3.11 and above

---

storages/backends/s3.py
tests/test_s3.py

Rebased version of #1352 
Closes #1351

[s3] Fix newline handling for text-mode files

---

docs/backends/amazon-S3.rst

Use correct variables according to the code, for `ACCESS_KEY` and `SECRET_KEY`

[s3] Fix wrong variable name

---

storages/backends/azure_storage.py
tests/test_azure.py

There is a ongoing issue with python manage.py collectstatic --clear
Due to Django trying to walk through every dir we just return all the files from the top dir.
That way we don't get a error when Django is trying to walk the files.
Tested with --clear and without --clear.

Fixing the problem that arises when using --clear in python manage.py collectstatic

---

CHANGELOG.rst
storages/backends/azure_storage.py
tests/test_azure.py

Allow creation of signed URLs for upload in AzureStorage (See #1413)

[azure] Allow creation of signed URLs for upload

---

CHANGELOG.rst
storages/backends/s3.py

This adds a class-level cache layer in front of cloudfront signers.  
Was debugging slowness on a django repo with 50 s3 storage fields, and the expensive `load_pem_private_key` was called for every field implementing the S3Storage class, even though the id/key was the same for each field.  This added a full 3 seconds to server start/restart time.
Caching seems desirable for all users of the library, will provide an instant speed benefit for current users, and will keep django apps snappy and responsive no matter how many filefields they add to their django project.

Caches Cloudfront Signers

---

storages/backends/azure_storage.py
storages/backends/dropbox.py
storages/backends/gcloud.py
storages/backends/s3.py
storages/utils.py
tests/test_azure.py
tests/test_dropbox.py
tests/test_gcloud.py
tests/test_s3.py
tests/test_utils.py

Follow upstream and write the file overwriting handling in terms of `exists()`.
Reference: https://github.com/django/django/commit/0b33a3abc2ca7d68a24f6d0772bc2b9fa603744e#diff-63fca472a0ca8c04505cb4ec9c132663ac71fc964110afc8ae9218416f37821cR195-R202

[general] Write overwriting files in terms of .exists()

---

CHANGELOG.rst
docs/backends/azure.rst
storages/backends/azure_storage.py
tests/test_azure.py

This allows users to customize how many times they want django-storages to retry failed requests to Azure Storage.
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-retry-policy-python#use-the-default-retry-policy
https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.exponentialretry?view=azure-python#parameters

[azure] Add AZURE_CLIENT_OPTIONS setting

---

storages/backends/ftp.py

We're using multiple different thirdparty ftp servers and we've now stumbled over a case, where the `.exists(name)` call did not work correctly.
In this case, the `location` looked like `ftp://username:password@example.org:21/`, so it CWDs to the root. In the root there were multiple files like 20240724.txt, 20240723.txt,...
When I used `storage.exists("20240724.txt")` it returned False (note, `allow_overwrite` was False). The problem with this setup is, that this exists-call resulted in the call of `self._connection.nlst("/")` (which is also not correct, if a different path/CWD is used), which returned a list with items like `["/20240724.txt", "/20240723.txt"]`, so all items have a "/" prepended, therefore the actual name "20240724.txt" cannot be found. This is not the case, when …

[ftp] Don't append slash to NLST in exists()

---

storages/backends/dropbox.py
tests/test_dropbox.py

[dropbox] Fix setting oauth2 access token via env var

---

pyproject.toml
storages/backends/gcloud.py
tests/test_gcloud.py

Python 3.10 and later versions rely on OpenSSL 1.1.1 or newer, which includes FIPS-compliance checks.
MD5 is not an approved algorithm in FIPS mode, so attempting to instantiate self.blob.download_to_file(self._file) will fail when the system is running in FIPS mode.
The change configures the `download_to_file` function to use an alternative algorithm provided by gcloud storage SDK - 'crc32c' - for checksum calculation.

Fix #1469 Use a different checksum calculation method to run in FIPS env

---

storages/backends/gcloud.py
tests/test_gcloud.py

The `self.blob.download_to_file` already performs decompression per this [StackOverflow](https://stackoverflow.com/questions/67744979/how-to-prevent-gcs-from-automatically-decompressing-objects-when-using-python-sd) post. Rather than attempting to decompress the gzip file a second time and receiving an error, allow `self.blob.download_to_file` to decompress it.
An alternative to this would be to use the `raw_download=True` kwarg for `self.blob.download_to_file` if that is desirable.
This closes #1456.

[gcloud] fix double decompression when using gzip

---

storages/utils.py
tests/test_utils.py

Fix for CVE-2024-39330 that I reported earlier, Django relied on non-overridden `get_available_name` for security which was overridden in this library. This is fixed on 4.2+.

[general] Apply additional validation in overwrite path

---

docs/backends/gcloud.rst
pyproject.toml
storages/backends/gcloud.py
tests/test_gcloud.py

fixes #941 
- Adds `sa_email` setting in order to set the service_account_email used for signing URL if service_account key file not available in the env. Compute services (Cloud Run, Cloud Function, App Engine, Compute Engine ...) don't have access to the key file but get access tokens through the metadata server. Passing service_account_email and access_token will cause generate_signed_url to use the IAM API to signBlob using the provided service account email and token.

Fix: Generate Signed Urls through a service account by providing service_account_email and access_token

---

docs/backends/gcloud.rst

[docs/gcloud] Clean-up querystring auth language

---

storages/backends/s3.py
tests/test_s3.py

When using server-side-encryption with customer-provided keys (SSE-C), the `head_object` call needs the SSE-C key and algorithm - otherwise the call will fail with `botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request` if the file already exists.
From the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html):
> If you encrypt an object by using server-side encryption with customer-provided encryption keys (SSE-C) when you store the object in Amazon S3, then when you retrieve the metadata from the object, you must use the following headers to provide the encryption key for the server to be able to retrieve the object's metadata. The headers are:
> - x-amz-server-side-encryption-customer-algorithm
> - …

[s3] Pass object parameters to head_object in `exists`

---

storages/backends/s3.py
tests/test_s3.py

We had a situation, that somebody put in our settings:
```
AWS_S3_URL_PROTOCOL = os.environ.get("AWS_S3_URL_PROTOCOL")
```
here it was falsely assumed, that not setting this environment variable will make `django-storages` to fallback to default `https:` (which didn't happened and we want to fix it in this pull request).

Defend against settings.AWS_S3_URL_PROTOCOL set to None

---

.github/workflows/ci.yml

Upgrade GitHub Actions Ubuntu version from 20.04 to 22.04
Ubuntu 20.04 (Focal Fossa) has reached end of support in GitHub Actions, so this PR updates our workflow configurations to use Ubuntu 22.04 (Jammy Jellyfish) instead.
This change ensures our CI/CD pipelines continue to run on a supported environment.
ref: https://github.com/actions/runner-images/issues/11101

[ci] Update CI to use Ubuntu 22.04 for testing

---

tests/test_s3.py
tox.ini

Add moto5 support
