jschneier/django-storages

README.rst
Currently it's a bit uncomfortable to look into to `setup.py` to find the version and even the *name* of the package.
=> Add PyPI banner

storages/backends/dropbox.py
Made some fix for compatibility with others backend.
=> Dropbox fix and improvement

docs/backends/dropbox.rst, storages/backends/dropbox.py, tests/test_dropbox.py
- Added ``ROOT_PATH`` option to jail storage in a storage
- Remove ``'/'`` prefixing all files and dirs
- Added Tests
- Added docs
=> Improved DropBox storage

setup.py
=> Document supported versions of Django in setup.py

storages/backends/s3boto3.py, tests/test_s3boto3.py
Fixes https://github.com/jschneier/django-storages/issues/194
=> Add support for files > 5 gb with S3BotoStorage

docs/backends/azure.rst
Add necessary steps for azure backend installation
Corresponds to https://github.com/jschneier/django-storages/issues/219
=> Add neccessary steps for azure backend installation

AUTHORS, storages/backends/s3boto3.py, tests/test_s3boto3.py
=> Fix S3Boto3: Double localtime call Exception on modified_time when USE_TZ=False 

requirements-tests.txt
Added google-cloud>=0.25.0 as test requirement
=> Add missing gcloud test requirements

.travis.yml, requirements-tests.txt, setup.cfg, setup.py, storages/backends/gcloud.py, storages/backends/gs.py, storages/backends/s3boto.py, tests/test_ftp.py, tests/test_gcloud.py, tests/test_sftp.py, tests/test_utils.py, tox.ini
Run flake8 with tests to help test for code consistency, conventions,
and code smells.
Fixed all existing flake8 errors:
* Duplicated function names
* Unused imports
* Unused variables
* Whitespace and styling conventions
=> Add flake8 to tox and Travis CI configuration

docs/backends/amazon-S3.rst
To help users who have the same issue than the one I described in #203
=> Improved S3 docs about Signature version

storages/backends/s3boto.py, storages/backends/s3boto3.py, tests/test_s3boto.py
Remove unnecessary lists, generators, and functions calls by using modern Python syntax: dict comprehension, set literals, dict literals.
=> Use dict comprehension and set literals

storages/backends/s3boto3.py
The indirection was necessary for the older s3boto backend as it shared code with the (now deprecated) GS backend. The s3boto3 does not share code in this way. When the s3boto3 was developed, the indirection was carried over, but it is no longer necessary. To simplify the code, remove it. Other backends do not encode this style of indirection.
=> Remove unnecessary indirection in s3boto3 backend

AUTHORS
For patches contributed, see:
https://github.com/jschneier/django-storages/commits?author=jdufresne
=> Add myself to the list of contributors

.travis.yml
Was previously missing Python 3.5.
=> Test the full test matrix using Travis

setup.py
Django is a requirement of django-storages, it should be listed as such.
=> Add Django to list of requirements in setup.py

docs/backends/gcloud.rst
Improve Google Cloud Documentation. In particular, add more detail on the setup of credentials (#455) and remove confusing reference to MyStorage (#475)
=> Documentation: Add more detail to Google Cloud setup.

storages/backends/sftpstorage.py, tests/test_sftp.py
=> call SFTPStorage._connect if ssh connection have been closed

storages/backends/s3boto3.py
=> S3Boto3: reraise unexpected exceptions during bucket creation

docs/backends/gcloud.rst
=> docs: new line to format properly numbered list

docs/backends/amazon-S3.rst
=> Make the examples Python 3 compatible

docs/backends/amazon-S3.rst, docs/backends/apache_libcloud.rst, docs/backends/azure.rst, docs/backends/ftp.rst, docs/backends/gcloud.rst, docs/backends/sftp.rst
Fixed some minor typo's and grammar for various documentation pages.
=> Fixed typo on various storage documentation pages.

storages/backends/s3boto3.py
=> Reuse Django's make_naive()

storages/backends/s3boto3.py
=> S3Boto3: remove entry from cache on delete when preload_metadata is True

tox.ini
=> Test against Django 3.0 final release

storages/backends/ftp.py
=> [ftp] Fix creating multiple intermediary directories on Windows

docs/backends/amazon-S3.rst, storages/backends/s3boto3.py
Closes #319
Closes #391 
Closes #819
=> [s3] Add overrideable method to customize parameters on a per-key basis

storages/backends/s3boto3.py
=> [s3] Fix reading files with S3Boto3StorageFile

docs/backends/amazon-S3.rst
=> Fix simple typo: specifiy -> specify

storages/backends/dropbox.py, storages/backends/sftpstorage.py, storages/base.py
pyupgrade is a tool to automatically upgrade syntax for newer versions
of the language.
For more details, see:
https://github.com/asottile/pyupgrade
=> Run pyupgrade on the project to update Python syntax and conventions

docs/backends/gcloud.rst, storages/backends/gcloud.py, storages/backends/s3boto3.py
There were missed when automatic bucket creation was removed.
=> Remove auto creation ACL settings & documentation

docs/backends/amazon-S3.rst, docs/backends/gcloud.rst
django-admin.py has been deprecated since upstream commit:
https://github.com/django/django/commit/5708327c3769262b845730996ca2784245ada4d1
=> Replace deprecated django-admin.py with django-admin

docs/backends/amazon-S3.rst
=> Docs: Fix block highlighting

storages/backends/s3boto3.py
=> Use context manager with GzipFile

CHANGELOG.rst, storages/backends/azure_storage.py, tests/test_azure.py
=> Azure: fix use of custom domain with account key

docs/backends/azure.rst, storages/backends/azure_storage.py
Restored support for endpoint_suffix in previous PR. Now adding endpoint_suffix to Azure docs.
=> Add endpoint_suffix to Azure docs

CHANGELOG.rst, storages/backends/dropbox.py, tests/test_dropbox.py
=> [dropbox] fix saving files

docs/backends/azure.rst
There's a code block that's currently not rendering as one due to a missing new line, so that's the main fix of this PR. Also fixed a django capitalization while I was in there.
=> Fix code block

docs/backends/amazon-S3.rst, docs/backends/apache_libcloud.rst, docs/backends/azure.rst, docs/backends/dropbox.rst, docs/backends/ftp.rst, docs/backends/gcloud.rst
No code changes are required to make django-storages compatible with the new setting.
Resolves https://github.com/jschneier/django-storages/issues/1207
=> Document usage with STORAGES setting

docs/backends/amazon-S3.rst
=> Update docs - Overriding the default Storage class in AWS S3 Bucket

storages/backends/s3boto3.py
=> [s3] do not try to decompress files opened in write mode

storages/backends/s3boto3.py, tests/test_s3boto3.py
=> [s3] do not override a returned ContentType from get_object_parameters

docs/backends/amazon-S3.rst, setup.cfg
=> [s3] add s3 extras_require

docs/backends/amazon-S3.rst, docs/backends/azure.rst, docs/backends/backblaze-B2.rst, docs/backends/digital-ocean-spaces.rst, docs/backends/dropbox.rst, docs/backends/gcloud.rst, docs/backends/oracle-cloud.rst, docs/backends/sftp.rst
=> [docs] document OPTIONS settings

storages/backends/s3boto3.py, tests/test_s3boto3.py
=> [s3] fix support for retrieving SSE-C files

docs/backends/amazon-S3.rst
To one that has which signatures can be used where.
=> Update link to S3 region list

storages/backends/s3.py
=> [s3] fix crash when cleaning up after aborted connection

CHANGELOG.rst, storages/backends/s3.py, tests/test_s3.py
=> [s3] Skip generating signed URLs if querystring_auth=False

CHANGELOG.rst, docs/backends/ftp.rst, storages/backends/ftp.py, tests/test_ftp.py
=> [ftp] Add FTP_ALLOW_OVERWRITE setting

tests/test_gcloud.py
=> Fix Google Cloud tests

storages/backends/azure_storage.py, storages/backends/dropbox.py, storages/backends/gcloud.py, storages/backends/s3.py, storages/utils.py, tests/test_azure.py, tests/test_dropbox.py, tests/test_gcloud.py, tests/test_s3.py, tests/test_utils.py
This reverts commit a5319477473e5bab60b0d698e2a8127a8f750787.
Closes #1430
=> Revert "[general] Write overwriting files in terms of .exists() (#1422)"

docs/backends/azure.rst
Updated dead Microsoft docs link for configuring a connection string for an Azure storage account.
=> Updated old docs link

.github/workflows/ci.yml, CHANGELOG.rst, pyproject.toml, tox.ini
closes #1511 
original pr author: @kimihito 
orignal pr: #1501
=> Add support for Django 5.2

docs/backends/s3_compatible/cloudflare-r2.rst
Updated documentation to reflect the need to add a custom domain in the cloudflare dashboard.
=> Update docs for Cloudflare R2
